language: ruby
rvm:
  - 2.4
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - secure: <secure $DEPLOY_USER>=admin
    - secure: <secure $DEPLOY_HOST>=devinsipal.com
    - secure: <secure $DEPLOY_DIRECTORY>=/home/admin/devinsipal.com/public_html
branches:
  only:
    - master
script:
  - bundle exec jekyll build
  - bundle exec rake test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_<stuff>_key -iv $encrypted_<stuff>_iv
    -in ./deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e
    "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after _site/*
    $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master