title: devinsipal.com
email: devin@devinsipal.com

description: >-
    I am a digital artist utilizing video, audio, photo, and code. From a young age I was always fascinated by computers; with the gift of a Visual Basic game programming book around age 8 I was plunged into a world of creating multimedia experiences. For me, the line between analytical and creative thinking is blurred- I prefer to operate in between the two.
baseurl: ""
url: "https://devinsipal.com"
permalink: '/:categories/:title/'
# Build settings
markdown: kramdown
theme: devinsipal
plugins:
  - jekyll-feed
  - jekyll-bootstrap-sass
  - jekyll-paginate-v2
sass:
  style: compact
  sass_dir: ./_sass
pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  layout: category

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
