title: devinsipal.com
email: devin@devinsipal.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://devinsipal.com" # the base hostname & protocol for your site, e.g. http://example.com


twitter_username: dsipal
github_username:  dsipal
linkedin_username: devin-sipal-721285106

# Build settings
markdown: kramdown
theme: devinsipal
plugins:
  - jekyll-feed
  - bootstrap-sass
  - jekyll-bootstrap-sass

sass:
  style: compact
  sass_dir: ./_sass

collections:
  category:
    output: true
    permalink: /:name/


defaults:
  - scope:
      path: ""
      type: "category"
    values:
      layout: category

permalink: none


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
