title: devinsipal.com
email: devin@devinsipal.com
description: >-
  Devin Sipal has a wide variety of styles they tap into. Utilizing both video and code as a medium, they bring a fresh take to both areas. Having started programming at a very young age, they have an intense passion for working with computers to create art.
baseurl: ""
url: "http://devinsipal.com"


twitter_username: dsipal
github_username:  dsipal
linkedin_username: devin-sipal-721285106

# Build settings
markdown: kramdown
theme: devinsipal
plugins:
  - jekyll-feed
  - bootstrap-sass
  - jekyll-bootstrap-sass

sass:
  style: compact
  sass_dir: ./_sass

collections:
  category:
    output: true
    permalink: /:name/


defaults:
  - scope:
      path: ""
      type: "category"
    values:
      layout: category

permalink: none


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
