title: devinsipal.com
email: devin@devinsipal.com

description: >-
  Devin Sipal has a wide variety of styles they tap into. Utilizing both video and code as a medium, they bring a fresh take to both areas. Having started programming at a very young age, they have an intense passion for working with computers to create art.

baseurl: ""
url: "http://devinsipal.com"

permalink: '/:i_month/:title'


# Build settings
markdown: kramdown
theme: devinsipal
plugins:
  - jekyll-feed
  - bootstrap-sass
  - jekyll-bootstrap-sass
  - jekyll-paginate-v2

sass:
  style: compact
  sass_dir: ./_sass

pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  layout: category

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
